### ISSUE TITLE
Would love an updated version

### ISSUE THREAD

**Issue by 3nigm4** [thomasnield/rxkotlinfx-tornadofx-demo#2]
Hello, huge thanks for the demo. Would love to see this with updated dependencies. A lot of stuff breaks with current libraries and I am to new to kotlin to know where everything went ... thanks!

**Comment by thomasnield** [comment]
I updated all dependencies and refactored out the compile errors. 

I am getting some runtime errors due to RxKotlin-JDBC. I'll investigate what's up with this, because I need to make sure that library is working too.

**Comment by thomasnield** [comment]
Update is complete. Application is now working with RxJava 2.x and latest dependencies.
